# Generated by Django 3.0.8 on 2020-10-24 12:19

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthNewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Health News Category',
                'verbose_name_plural': 'Health News Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HealthNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=1000)),
                ('list_description', models.CharField(max_length=1000)),
                ('detail_description', djrichtextfield.models.RichTextField()),
                ('slug', models.SlugField()),
                ('categories', models.ManyToManyField(related_name='healthnews', to='health_news.HealthNewsCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Health News',
                'verbose_name_plural': 'Health News',
                'ordering': ['title'],
            },
        ),
    ]
