# Generated by Django 3.0.8 on 2020-10-30 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_news', '0002_auto_20201024_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthnews',
            name='categories',
        ),
        migrations.AddField(
            model_name='healthnews',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='health_news.Category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
