# Generated by Django 3.0.8 on 2020-10-30 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_news', '0003_auto_20201030_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthnews',
            old_name='category',
            new_name='newscategory',
        ),
    ]
