# Generated by Django 3.0.8 on 2020-10-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_news', '0004_auto_20201030_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthnews',
            old_name='newscategory',
            new_name='category',
        ),
    ]
