# Generated by Django 3.1.1 on 2020-11-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_news', '0007_auto_20201104_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthnews',
            options={'ordering': ['title'], 'verbose_name': 'Health News', 'verbose_name_plural': 'Health News'},
        ),
    ]
