# Generated by Django 3.1.1 on 2021-02-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_news', '0008_auto_20201104_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthnews',
            name='detail_description',
            field=models.TextField(max_length=1000000),
        ),
    ]
