# Generated by Django 3.0.8 on 2020-11-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lingfield', '0002_auto_20201101_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
