# Generated by Django 3.1.1 on 2021-02-21 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0005_remove_medicine_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=1000)),
                ('hospital', models.CharField(max_length=1000)),
                ('hospital_street', models.CharField(max_length=1000)),
                ('district', models.CharField(blank=True, max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('postal_code', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('reminder', models.CharField(choices=[('Never', 'Never'), ('Once', 'Once'), ('Regularly', 'Regularly')], default='None', max_length=30)),
                ('added', models.BooleanField(default=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicine Item',
                'verbose_name_plural': 'Medicine Items',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_no', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('nhs_no', models.CharField(max_length=10000)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('uk_postcode_lookup', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=1000)),
                ('street', models.CharField(max_length=2000)),
                ('town', models.CharField(max_length=1000)),
                ('county', models.CharField(max_length=1000)),
                ('postcode', models.CharField(max_length=1000)),
                ('one_click_purchasing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBirthDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbirthdate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectSurgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.BooleanField(default=False)),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitallist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('medicine_items', models.ManyToManyField(to='accounts.MedicineItems')),
                ('selected_surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.selectsurgery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receival', models.CharField(choices=[('Courier', 'Courier')], default='Courier', max_length=30)),
                ('prescription_note', models.CharField(max_length=1000)),
                ('delivery_note', models.CharField(max_length=1000)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.prescriptionitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=1000)),
                ('first_name', models.CharField(max_length=1000)),
                ('middle_names', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('landline_telephone_no', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('nhs_no', models.CharField(max_length=10000)),
                ('notes', models.TextField(max_length=100000)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('street', models.CharField(max_length=2000)),
                ('town', models.CharField(max_length=1000)),
                ('county', models.CharField(max_length=1000)),
                ('postcode', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddSurgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_name', models.CharField(max_length=1000)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('uk_postcode_lookup', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=2000)),
                ('saved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addsurgery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Add Surgery',
                'verbose_name_plural': 'Add Surgeries',
            },
        ),
    ]
