# Generated by Django 3.1.1 on 2021-02-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='items',
        ),
        migrations.AddField(
            model_name='prescription',
            name='items',
            field=models.ManyToManyField(to='accounts.PrescriptionItem'),
        ),
    ]
