# Generated by Django 3.0.8 on 2020-10-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Health Advice',
                'verbose_name_plural': 'Health Advices',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HealthAdviceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Health Advice Category',
                'verbose_name_plural': 'Health Advice Categories',
                'ordering': ['title'],
            },
        ),
    ]
