# Generated by Django 3.0.8 on 2020-10-23 21:58

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('health_advice', '0003_auto_20201023_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthadvice',
            name='detail_description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
