# Generated by Django 3.0.8 on 2020-10-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_advice', '0004_auto_20201023_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthadvice',
            name='category',
        ),
        migrations.AddField(
            model_name='healthadvice',
            name='categories',
            field=models.ManyToManyField(related_name='healthadvices', to='health_advice.HealthAdviceCategory', verbose_name='HealthAdviceCategory'),
        ),
    ]
