# Generated by Django 3.0.8 on 2020-10-24 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_advice', '0007_auto_20201024_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthadvice',
            name='categories',
        ),
        migrations.AddField(
            model_name='healthadvice',
            name='categories',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='health_advice.Category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
