# Generated by Django 3.0.8 on 2020-10-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_advice', '0008_auto_20201024_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthadvice',
            old_name='categories',
            new_name='category',
        ),
    ]
