# Generated by Django 3.0.8 on 2020-10-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_advice', '0010_auto_20201030_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthadvice',
            old_name='categories',
            new_name='category',
        ),
    ]
