# Generated by Django 3.1.1 on 2021-02-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_advice', '0011_auto_20201030_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthadvice',
            name='detail_description',
            field=models.TextField(max_length=100000000),
        ),
    ]
