# Generated by Django 3.0.8 on 2020-10-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicines.Category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
