# Generated by Django 3.1.1 on 2021-02-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_remove_medicine_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='detail_description',
            field=models.TextField(max_length=1000000),
        ),
    ]
