# Generated by Django 3.1.1 on 2020-12-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20201214_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shipping_cost',
            field=models.FloatField(),
        ),
    ]
