# Generated by Django 3.1.1 on 2020-12-14 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20201214_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
