# Generated by Django 3.1.1 on 2021-02-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_delete_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='category',
        ),
    ]
